// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PivotImagesResponse.proto

package com.yzh.cqjw.response;

public final class PivotImagesResponse {
  private PivotImagesResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PivotImagesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PivotImages)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 picID = 1;</code>
     */
    int getPicID();

    /**
     * <code>optional int32 pivotID = 2;</code>
     */
    int getPivotID();

    /**
     * <code>optional string picURL = 3;</code>
     */
    java.lang.String getPicURL();
    /**
     * <code>optional string picURL = 3;</code>
     */
    com.google.protobuf.ByteString
        getPicURLBytes();

    /**
     * <code>optional string picDESC = 4;</code>
     */
    java.lang.String getPicDESC();
    /**
     * <code>optional string picDESC = 4;</code>
     */
    com.google.protobuf.ByteString
        getPicDESCBytes();
  }
  /**
   * Protobuf type {@code PivotImages}
   */
  public  static final class PivotImages extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PivotImages)
      PivotImagesOrBuilder {
    // Use PivotImages.newBuilder() to construct.
    private PivotImages(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PivotImages() {
      picID_ = 0;
      pivotID_ = 0;
      picURL_ = "";
      picDESC_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PivotImages(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              picID_ = input.readInt32();
              break;
            }
            case 16: {

              pivotID_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              picURL_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              picDESC_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.cqjw.response.PivotImagesResponse.internal_static_PivotImages_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.cqjw.response.PivotImagesResponse.internal_static_PivotImages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.cqjw.response.PivotImagesResponse.PivotImages.class, com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder.class);
    }

    public static final int PICID_FIELD_NUMBER = 1;
    private int picID_;
    /**
     * <code>optional int32 picID = 1;</code>
     */
    public int getPicID() {
      return picID_;
    }

    public static final int PIVOTID_FIELD_NUMBER = 2;
    private int pivotID_;
    /**
     * <code>optional int32 pivotID = 2;</code>
     */
    public int getPivotID() {
      return pivotID_;
    }

    public static final int PICURL_FIELD_NUMBER = 3;
    private volatile java.lang.Object picURL_;
    /**
     * <code>optional string picURL = 3;</code>
     */
    public java.lang.String getPicURL() {
      java.lang.Object ref = picURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        picURL_ = s;
        return s;
      }
    }
    /**
     * <code>optional string picURL = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPicURLBytes() {
      java.lang.Object ref = picURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        picURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICDESC_FIELD_NUMBER = 4;
    private volatile java.lang.Object picDESC_;
    /**
     * <code>optional string picDESC = 4;</code>
     */
    public java.lang.String getPicDESC() {
      java.lang.Object ref = picDESC_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        picDESC_ = s;
        return s;
      }
    }
    /**
     * <code>optional string picDESC = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPicDESCBytes() {
      java.lang.Object ref = picDESC_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        picDESC_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (picID_ != 0) {
        output.writeInt32(1, picID_);
      }
      if (pivotID_ != 0) {
        output.writeInt32(2, pivotID_);
      }
      if (!getPicURLBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, picURL_);
      }
      if (!getPicDESCBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, picDESC_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (picID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, picID_);
      }
      if (pivotID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pivotID_);
      }
      if (!getPicURLBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, picURL_);
      }
      if (!getPicDESCBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, picDESC_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.cqjw.response.PivotImagesResponse.PivotImages)) {
        return super.equals(obj);
      }
      com.yzh.cqjw.response.PivotImagesResponse.PivotImages other = (com.yzh.cqjw.response.PivotImagesResponse.PivotImages) obj;

      boolean result = true;
      result = result && (getPicID()
          == other.getPicID());
      result = result && (getPivotID()
          == other.getPivotID());
      result = result && getPicURL()
          .equals(other.getPicURL());
      result = result && getPicDESC()
          .equals(other.getPicDESC());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PICID_FIELD_NUMBER;
      hash = (53 * hash) + getPicID();
      hash = (37 * hash) + PIVOTID_FIELD_NUMBER;
      hash = (53 * hash) + getPivotID();
      hash = (37 * hash) + PICURL_FIELD_NUMBER;
      hash = (53 * hash) + getPicURL().hashCode();
      hash = (37 * hash) + PICDESC_FIELD_NUMBER;
      hash = (53 * hash) + getPicDESC().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.cqjw.response.PivotImagesResponse.PivotImages prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PivotImages}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PivotImages)
        com.yzh.cqjw.response.PivotImagesResponse.PivotImagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.cqjw.response.PivotImagesResponse.internal_static_PivotImages_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.cqjw.response.PivotImagesResponse.internal_static_PivotImages_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.cqjw.response.PivotImagesResponse.PivotImages.class, com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder.class);
      }

      // Construct using com.yzh.cqjw.response.PivotImagesResponse.PivotImages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        picID_ = 0;

        pivotID_ = 0;

        picURL_ = "";

        picDESC_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.cqjw.response.PivotImagesResponse.internal_static_PivotImages_descriptor;
      }

      public com.yzh.cqjw.response.PivotImagesResponse.PivotImages getDefaultInstanceForType() {
        return com.yzh.cqjw.response.PivotImagesResponse.PivotImages.getDefaultInstance();
      }

      public com.yzh.cqjw.response.PivotImagesResponse.PivotImages build() {
        com.yzh.cqjw.response.PivotImagesResponse.PivotImages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.cqjw.response.PivotImagesResponse.PivotImages buildPartial() {
        com.yzh.cqjw.response.PivotImagesResponse.PivotImages result = new com.yzh.cqjw.response.PivotImagesResponse.PivotImages(this);
        result.picID_ = picID_;
        result.pivotID_ = pivotID_;
        result.picURL_ = picURL_;
        result.picDESC_ = picDESC_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.cqjw.response.PivotImagesResponse.PivotImages) {
          return mergeFrom((com.yzh.cqjw.response.PivotImagesResponse.PivotImages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.cqjw.response.PivotImagesResponse.PivotImages other) {
        if (other == com.yzh.cqjw.response.PivotImagesResponse.PivotImages.getDefaultInstance()) return this;
        if (other.getPicID() != 0) {
          setPicID(other.getPicID());
        }
        if (other.getPivotID() != 0) {
          setPivotID(other.getPivotID());
        }
        if (!other.getPicURL().isEmpty()) {
          picURL_ = other.picURL_;
          onChanged();
        }
        if (!other.getPicDESC().isEmpty()) {
          picDESC_ = other.picDESC_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.cqjw.response.PivotImagesResponse.PivotImages parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.cqjw.response.PivotImagesResponse.PivotImages) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int picID_ ;
      /**
       * <code>optional int32 picID = 1;</code>
       */
      public int getPicID() {
        return picID_;
      }
      /**
       * <code>optional int32 picID = 1;</code>
       */
      public Builder setPicID(int value) {
        
        picID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 picID = 1;</code>
       */
      public Builder clearPicID() {
        
        picID_ = 0;
        onChanged();
        return this;
      }

      private int pivotID_ ;
      /**
       * <code>optional int32 pivotID = 2;</code>
       */
      public int getPivotID() {
        return pivotID_;
      }
      /**
       * <code>optional int32 pivotID = 2;</code>
       */
      public Builder setPivotID(int value) {
        
        pivotID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pivotID = 2;</code>
       */
      public Builder clearPivotID() {
        
        pivotID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object picURL_ = "";
      /**
       * <code>optional string picURL = 3;</code>
       */
      public java.lang.String getPicURL() {
        java.lang.Object ref = picURL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          picURL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string picURL = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPicURLBytes() {
        java.lang.Object ref = picURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          picURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string picURL = 3;</code>
       */
      public Builder setPicURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        picURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string picURL = 3;</code>
       */
      public Builder clearPicURL() {
        
        picURL_ = getDefaultInstance().getPicURL();
        onChanged();
        return this;
      }
      /**
       * <code>optional string picURL = 3;</code>
       */
      public Builder setPicURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        picURL_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object picDESC_ = "";
      /**
       * <code>optional string picDESC = 4;</code>
       */
      public java.lang.String getPicDESC() {
        java.lang.Object ref = picDESC_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          picDESC_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string picDESC = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPicDESCBytes() {
        java.lang.Object ref = picDESC_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          picDESC_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string picDESC = 4;</code>
       */
      public Builder setPicDESC(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        picDESC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string picDESC = 4;</code>
       */
      public Builder clearPicDESC() {
        
        picDESC_ = getDefaultInstance().getPicDESC();
        onChanged();
        return this;
      }
      /**
       * <code>optional string picDESC = 4;</code>
       */
      public Builder setPicDESCBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        picDESC_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PivotImages)
    }

    // @@protoc_insertion_point(class_scope:PivotImages)
    private static final com.yzh.cqjw.response.PivotImagesResponse.PivotImages DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.cqjw.response.PivotImagesResponse.PivotImages();
    }

    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImages getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PivotImages>
        PARSER = new com.google.protobuf.AbstractParser<PivotImages>() {
      public PivotImages parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PivotImages(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PivotImages> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PivotImages> getParserForType() {
      return PARSER;
    }

    public com.yzh.cqjw.response.PivotImagesResponse.PivotImages getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PivotImagesResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PivotImagesResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage getErrorMsg();
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder();

    /**
     * <code>repeated .PivotImages pivotImages = 2;</code>
     */
    java.util.List<com.yzh.cqjw.response.PivotImagesResponse.PivotImages> 
        getPivotImagesList();
    /**
     * <code>repeated .PivotImages pivotImages = 2;</code>
     */
    com.yzh.cqjw.response.PivotImagesResponse.PivotImages getPivotImages(int index);
    /**
     * <code>repeated .PivotImages pivotImages = 2;</code>
     */
    int getPivotImagesCount();
    /**
     * <code>repeated .PivotImages pivotImages = 2;</code>
     */
    java.util.List<? extends com.yzh.cqjw.response.PivotImagesResponse.PivotImagesOrBuilder> 
        getPivotImagesOrBuilderList();
    /**
     * <code>repeated .PivotImages pivotImages = 2;</code>
     */
    com.yzh.cqjw.response.PivotImagesResponse.PivotImagesOrBuilder getPivotImagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PivotImagesResponseMessage}
   */
  public  static final class PivotImagesResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PivotImagesResponseMessage)
      PivotImagesResponseMessageOrBuilder {
    // Use PivotImagesResponseMessage.newBuilder() to construct.
    private PivotImagesResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PivotImagesResponseMessage() {
      pivotImages_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PivotImagesResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.Builder subBuilder = null;
              if (errorMsg_ != null) {
                subBuilder = errorMsg_.toBuilder();
              }
              errorMsg_ = input.readMessage(com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errorMsg_);
                errorMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                pivotImages_ = new java.util.ArrayList<com.yzh.cqjw.response.PivotImagesResponse.PivotImages>();
                mutable_bitField0_ |= 0x00000002;
              }
              pivotImages_.add(
                  input.readMessage(com.yzh.cqjw.response.PivotImagesResponse.PivotImages.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          pivotImages_ = java.util.Collections.unmodifiableList(pivotImages_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.cqjw.response.PivotImagesResponse.internal_static_PivotImagesResponseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.cqjw.response.PivotImagesResponse.internal_static_PivotImagesResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage.class, com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORMSG_FIELD_NUMBER = 1;
    private com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage errorMsg_;
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public boolean hasErrorMsg() {
      return errorMsg_ != null;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
      return errorMsg_ == null ? com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
    }
    /**
     * <code>optional .ErrorMessage errorMsg = 1;</code>
     */
    public com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
      return getErrorMsg();
    }

    public static final int PIVOTIMAGES_FIELD_NUMBER = 2;
    private java.util.List<com.yzh.cqjw.response.PivotImagesResponse.PivotImages> pivotImages_;
    /**
     * <code>repeated .PivotImages pivotImages = 2;</code>
     */
    public java.util.List<com.yzh.cqjw.response.PivotImagesResponse.PivotImages> getPivotImagesList() {
      return pivotImages_;
    }
    /**
     * <code>repeated .PivotImages pivotImages = 2;</code>
     */
    public java.util.List<? extends com.yzh.cqjw.response.PivotImagesResponse.PivotImagesOrBuilder> 
        getPivotImagesOrBuilderList() {
      return pivotImages_;
    }
    /**
     * <code>repeated .PivotImages pivotImages = 2;</code>
     */
    public int getPivotImagesCount() {
      return pivotImages_.size();
    }
    /**
     * <code>repeated .PivotImages pivotImages = 2;</code>
     */
    public com.yzh.cqjw.response.PivotImagesResponse.PivotImages getPivotImages(int index) {
      return pivotImages_.get(index);
    }
    /**
     * <code>repeated .PivotImages pivotImages = 2;</code>
     */
    public com.yzh.cqjw.response.PivotImagesResponse.PivotImagesOrBuilder getPivotImagesOrBuilder(
        int index) {
      return pivotImages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorMsg_ != null) {
        output.writeMessage(1, getErrorMsg());
      }
      for (int i = 0; i < pivotImages_.size(); i++) {
        output.writeMessage(2, pivotImages_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrorMsg());
      }
      for (int i = 0; i < pivotImages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pivotImages_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage)) {
        return super.equals(obj);
      }
      com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage other = (com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage) obj;

      boolean result = true;
      result = result && (hasErrorMsg() == other.hasErrorMsg());
      if (hasErrorMsg()) {
        result = result && getErrorMsg()
            .equals(other.getErrorMsg());
      }
      result = result && getPivotImagesList()
          .equals(other.getPivotImagesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasErrorMsg()) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
      }
      if (getPivotImagesCount() > 0) {
        hash = (37 * hash) + PIVOTIMAGES_FIELD_NUMBER;
        hash = (53 * hash) + getPivotImagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PivotImagesResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PivotImagesResponseMessage)
        com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.cqjw.response.PivotImagesResponse.internal_static_PivotImagesResponseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.cqjw.response.PivotImagesResponse.internal_static_PivotImagesResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage.class, com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage.Builder.class);
      }

      // Construct using com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPivotImagesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }
        if (pivotImagesBuilder_ == null) {
          pivotImages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          pivotImagesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.cqjw.response.PivotImagesResponse.internal_static_PivotImagesResponseMessage_descriptor;
      }

      public com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage getDefaultInstanceForType() {
        return com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage.getDefaultInstance();
      }

      public com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage build() {
        com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage buildPartial() {
        com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage result = new com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (errorMsgBuilder_ == null) {
          result.errorMsg_ = errorMsg_;
        } else {
          result.errorMsg_ = errorMsgBuilder_.build();
        }
        if (pivotImagesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            pivotImages_ = java.util.Collections.unmodifiableList(pivotImages_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.pivotImages_ = pivotImages_;
        } else {
          result.pivotImages_ = pivotImagesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage) {
          return mergeFrom((com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage other) {
        if (other == com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage.getDefaultInstance()) return this;
        if (other.hasErrorMsg()) {
          mergeErrorMsg(other.getErrorMsg());
        }
        if (pivotImagesBuilder_ == null) {
          if (!other.pivotImages_.isEmpty()) {
            if (pivotImages_.isEmpty()) {
              pivotImages_ = other.pivotImages_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePivotImagesIsMutable();
              pivotImages_.addAll(other.pivotImages_);
            }
            onChanged();
          }
        } else {
          if (!other.pivotImages_.isEmpty()) {
            if (pivotImagesBuilder_.isEmpty()) {
              pivotImagesBuilder_.dispose();
              pivotImagesBuilder_ = null;
              pivotImages_ = other.pivotImages_;
              bitField0_ = (bitField0_ & ~0x00000002);
              pivotImagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPivotImagesFieldBuilder() : null;
            } else {
              pivotImagesBuilder_.addAllMessages(other.pivotImages_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage errorMsg_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage, com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessageOrBuilder> errorMsgBuilder_;
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public boolean hasErrorMsg() {
        return errorMsgBuilder_ != null || errorMsg_ != null;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage getErrorMsg() {
        if (errorMsgBuilder_ == null) {
          return errorMsg_ == null ? com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        } else {
          return errorMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errorMsg_ = value;
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder setErrorMsg(
          com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.Builder builderForValue) {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = builderForValue.build();
          onChanged();
        } else {
          errorMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder mergeErrorMsg(com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage value) {
        if (errorMsgBuilder_ == null) {
          if (errorMsg_ != null) {
            errorMsg_ =
              com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.newBuilder(errorMsg_).mergeFrom(value).buildPartial();
          } else {
            errorMsg_ = value;
          }
          onChanged();
        } else {
          errorMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public Builder clearErrorMsg() {
        if (errorMsgBuilder_ == null) {
          errorMsg_ = null;
          onChanged();
        } else {
          errorMsg_ = null;
          errorMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.Builder getErrorMsgBuilder() {
        
        onChanged();
        return getErrorMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      public com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessageOrBuilder getErrorMsgOrBuilder() {
        if (errorMsgBuilder_ != null) {
          return errorMsgBuilder_.getMessageOrBuilder();
        } else {
          return errorMsg_ == null ?
              com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.getDefaultInstance() : errorMsg_;
        }
      }
      /**
       * <code>optional .ErrorMessage errorMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage, com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessageOrBuilder> 
          getErrorMsgFieldBuilder() {
        if (errorMsgBuilder_ == null) {
          errorMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage, com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessage.Builder, com.yzh.cqjw.response.ErrorMessageResponse.ErrorMessageOrBuilder>(
                  getErrorMsg(),
                  getParentForChildren(),
                  isClean());
          errorMsg_ = null;
        }
        return errorMsgBuilder_;
      }

      private java.util.List<com.yzh.cqjw.response.PivotImagesResponse.PivotImages> pivotImages_ =
        java.util.Collections.emptyList();
      private void ensurePivotImagesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          pivotImages_ = new java.util.ArrayList<com.yzh.cqjw.response.PivotImagesResponse.PivotImages>(pivotImages_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.cqjw.response.PivotImagesResponse.PivotImages, com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder, com.yzh.cqjw.response.PivotImagesResponse.PivotImagesOrBuilder> pivotImagesBuilder_;

      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public java.util.List<com.yzh.cqjw.response.PivotImagesResponse.PivotImages> getPivotImagesList() {
        if (pivotImagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pivotImages_);
        } else {
          return pivotImagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public int getPivotImagesCount() {
        if (pivotImagesBuilder_ == null) {
          return pivotImages_.size();
        } else {
          return pivotImagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public com.yzh.cqjw.response.PivotImagesResponse.PivotImages getPivotImages(int index) {
        if (pivotImagesBuilder_ == null) {
          return pivotImages_.get(index);
        } else {
          return pivotImagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public Builder setPivotImages(
          int index, com.yzh.cqjw.response.PivotImagesResponse.PivotImages value) {
        if (pivotImagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePivotImagesIsMutable();
          pivotImages_.set(index, value);
          onChanged();
        } else {
          pivotImagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public Builder setPivotImages(
          int index, com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder builderForValue) {
        if (pivotImagesBuilder_ == null) {
          ensurePivotImagesIsMutable();
          pivotImages_.set(index, builderForValue.build());
          onChanged();
        } else {
          pivotImagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public Builder addPivotImages(com.yzh.cqjw.response.PivotImagesResponse.PivotImages value) {
        if (pivotImagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePivotImagesIsMutable();
          pivotImages_.add(value);
          onChanged();
        } else {
          pivotImagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public Builder addPivotImages(
          int index, com.yzh.cqjw.response.PivotImagesResponse.PivotImages value) {
        if (pivotImagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePivotImagesIsMutable();
          pivotImages_.add(index, value);
          onChanged();
        } else {
          pivotImagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public Builder addPivotImages(
          com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder builderForValue) {
        if (pivotImagesBuilder_ == null) {
          ensurePivotImagesIsMutable();
          pivotImages_.add(builderForValue.build());
          onChanged();
        } else {
          pivotImagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public Builder addPivotImages(
          int index, com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder builderForValue) {
        if (pivotImagesBuilder_ == null) {
          ensurePivotImagesIsMutable();
          pivotImages_.add(index, builderForValue.build());
          onChanged();
        } else {
          pivotImagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public Builder addAllPivotImages(
          java.lang.Iterable<? extends com.yzh.cqjw.response.PivotImagesResponse.PivotImages> values) {
        if (pivotImagesBuilder_ == null) {
          ensurePivotImagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pivotImages_);
          onChanged();
        } else {
          pivotImagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public Builder clearPivotImages() {
        if (pivotImagesBuilder_ == null) {
          pivotImages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          pivotImagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public Builder removePivotImages(int index) {
        if (pivotImagesBuilder_ == null) {
          ensurePivotImagesIsMutable();
          pivotImages_.remove(index);
          onChanged();
        } else {
          pivotImagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder getPivotImagesBuilder(
          int index) {
        return getPivotImagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public com.yzh.cqjw.response.PivotImagesResponse.PivotImagesOrBuilder getPivotImagesOrBuilder(
          int index) {
        if (pivotImagesBuilder_ == null) {
          return pivotImages_.get(index);  } else {
          return pivotImagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public java.util.List<? extends com.yzh.cqjw.response.PivotImagesResponse.PivotImagesOrBuilder> 
           getPivotImagesOrBuilderList() {
        if (pivotImagesBuilder_ != null) {
          return pivotImagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pivotImages_);
        }
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder addPivotImagesBuilder() {
        return getPivotImagesFieldBuilder().addBuilder(
            com.yzh.cqjw.response.PivotImagesResponse.PivotImages.getDefaultInstance());
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder addPivotImagesBuilder(
          int index) {
        return getPivotImagesFieldBuilder().addBuilder(
            index, com.yzh.cqjw.response.PivotImagesResponse.PivotImages.getDefaultInstance());
      }
      /**
       * <code>repeated .PivotImages pivotImages = 2;</code>
       */
      public java.util.List<com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder> 
           getPivotImagesBuilderList() {
        return getPivotImagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yzh.cqjw.response.PivotImagesResponse.PivotImages, com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder, com.yzh.cqjw.response.PivotImagesResponse.PivotImagesOrBuilder> 
          getPivotImagesFieldBuilder() {
        if (pivotImagesBuilder_ == null) {
          pivotImagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yzh.cqjw.response.PivotImagesResponse.PivotImages, com.yzh.cqjw.response.PivotImagesResponse.PivotImages.Builder, com.yzh.cqjw.response.PivotImagesResponse.PivotImagesOrBuilder>(
                  pivotImages_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          pivotImages_ = null;
        }
        return pivotImagesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PivotImagesResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:PivotImagesResponseMessage)
    private static final com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage();
    }

    public static com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PivotImagesResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<PivotImagesResponseMessage>() {
      public PivotImagesResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PivotImagesResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PivotImagesResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PivotImagesResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.cqjw.response.PivotImagesResponse.PivotImagesResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PivotImages_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PivotImages_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PivotImagesResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PivotImagesResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031PivotImagesResponse.proto\032\032ErrorMessag" +
      "eResponse.proto\"N\n\013PivotImages\022\r\n\005picID\030" +
      "\001 \001(\005\022\017\n\007pivotID\030\002 \001(\005\022\016\n\006picURL\030\003 \001(\t\022\017" +
      "\n\007picDESC\030\004 \001(\t\"`\n\032PivotImagesResponseMe" +
      "ssage\022\037\n\010errorMsg\030\001 \001(\0132\r.ErrorMessage\022!" +
      "\n\013pivotImages\030\002 \003(\0132\014.PivotImagesB,\n\025com" +
      ".yzh.cqjw.responseB\023PivotImagesResponseb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yzh.cqjw.response.ErrorMessageResponse.getDescriptor(),
        }, assigner);
    internal_static_PivotImages_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PivotImages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PivotImages_descriptor,
        new java.lang.String[] { "PicID", "PivotID", "PicURL", "PicDESC", });
    internal_static_PivotImagesResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PivotImagesResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PivotImagesResponseMessage_descriptor,
        new java.lang.String[] { "ErrorMsg", "PivotImages", });
    com.yzh.cqjw.response.ErrorMessageResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
