// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetHighSpeedSectionRequest.proto

package com.yzh.cqjw.request;

public final class GetHighSpeedSectionRequest {
  private GetHighSpeedSectionRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetHighSpeedSectionRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetHighSpeedSectionRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string version = 1;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>optional string version = 1;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     *平台
     * </pre>
     *
     * <code>optional string platform = 2;</code>
     */
    java.lang.String getPlatform();
    /**
     * <pre>
     *平台
     * </pre>
     *
     * <code>optional string platform = 2;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();

    /**
     * <pre>
     *登錄成功返回的會話
     * </pre>
     *
     * <code>optional string session = 3;</code>
     */
    java.lang.String getSession();
    /**
     * <pre>
     *登錄成功返回的會話
     * </pre>
     *
     * <code>optional string session = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionBytes();

    /**
     * <pre>
     *当前高速路段配置版本
     * </pre>
     *
     * <code>optional string sectionVersion = 4;</code>
     */
    java.lang.String getSectionVersion();
    /**
     * <pre>
     *当前高速路段配置版本
     * </pre>
     *
     * <code>optional string sectionVersion = 4;</code>
     */
    com.google.protobuf.ByteString
        getSectionVersionBytes();

    /**
     * <pre>
     *当前高速路站配置版本
     * </pre>
     *
     * <code>optional string stationVersion = 5;</code>
     */
    java.lang.String getStationVersion();
    /**
     * <pre>
     *当前高速路站配置版本
     * </pre>
     *
     * <code>optional string stationVersion = 5;</code>
     */
    com.google.protobuf.ByteString
        getStationVersionBytes();

    /**
     * <pre>
     *当前轴性版本
     * </pre>
     *
     * <code>optional string axialityVersion = 6;</code>
     */
    java.lang.String getAxialityVersion();
    /**
     * <pre>
     *当前轴性版本
     * </pre>
     *
     * <code>optional string axialityVersion = 6;</code>
     */
    com.google.protobuf.ByteString
        getAxialityVersionBytes();
  }
  /**
   * Protobuf type {@code GetHighSpeedSectionRequestMessage}
   */
  public  static final class GetHighSpeedSectionRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetHighSpeedSectionRequestMessage)
      GetHighSpeedSectionRequestMessageOrBuilder {
    // Use GetHighSpeedSectionRequestMessage.newBuilder() to construct.
    private GetHighSpeedSectionRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetHighSpeedSectionRequestMessage() {
      version_ = "";
      platform_ = "";
      session_ = "";
      sectionVersion_ = "";
      stationVersion_ = "";
      axialityVersion_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetHighSpeedSectionRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              platform_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              session_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              sectionVersion_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              stationVersion_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              axialityVersion_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.cqjw.request.GetHighSpeedSectionRequest.internal_static_GetHighSpeedSectionRequestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.cqjw.request.GetHighSpeedSectionRequest.internal_static_GetHighSpeedSectionRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage.class, com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private volatile java.lang.Object version_;
    /**
     * <code>optional string version = 1;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>optional string version = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORM_FIELD_NUMBER = 2;
    private volatile java.lang.Object platform_;
    /**
     * <pre>
     *平台
     * </pre>
     *
     * <code>optional string platform = 2;</code>
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *平台
     * </pre>
     *
     * <code>optional string platform = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object session_;
    /**
     * <pre>
     *登錄成功返回的會話
     * </pre>
     *
     * <code>optional string session = 3;</code>
     */
    public java.lang.String getSession() {
      java.lang.Object ref = session_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        session_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *登錄成功返回的會話
     * </pre>
     *
     * <code>optional string session = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionBytes() {
      java.lang.Object ref = session_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        session_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECTIONVERSION_FIELD_NUMBER = 4;
    private volatile java.lang.Object sectionVersion_;
    /**
     * <pre>
     *当前高速路段配置版本
     * </pre>
     *
     * <code>optional string sectionVersion = 4;</code>
     */
    public java.lang.String getSectionVersion() {
      java.lang.Object ref = sectionVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sectionVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *当前高速路段配置版本
     * </pre>
     *
     * <code>optional string sectionVersion = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSectionVersionBytes() {
      java.lang.Object ref = sectionVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sectionVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATIONVERSION_FIELD_NUMBER = 5;
    private volatile java.lang.Object stationVersion_;
    /**
     * <pre>
     *当前高速路站配置版本
     * </pre>
     *
     * <code>optional string stationVersion = 5;</code>
     */
    public java.lang.String getStationVersion() {
      java.lang.Object ref = stationVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stationVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *当前高速路站配置版本
     * </pre>
     *
     * <code>optional string stationVersion = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStationVersionBytes() {
      java.lang.Object ref = stationVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AXIALITYVERSION_FIELD_NUMBER = 6;
    private volatile java.lang.Object axialityVersion_;
    /**
     * <pre>
     *当前轴性版本
     * </pre>
     *
     * <code>optional string axialityVersion = 6;</code>
     */
    public java.lang.String getAxialityVersion() {
      java.lang.Object ref = axialityVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        axialityVersion_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *当前轴性版本
     * </pre>
     *
     * <code>optional string axialityVersion = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAxialityVersionBytes() {
      java.lang.Object ref = axialityVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        axialityVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
      }
      if (!getPlatformBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, platform_);
      }
      if (!getSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, session_);
      }
      if (!getSectionVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sectionVersion_);
      }
      if (!getStationVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, stationVersion_);
      }
      if (!getAxialityVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, axialityVersion_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
      }
      if (!getPlatformBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, platform_);
      }
      if (!getSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, session_);
      }
      if (!getSectionVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sectionVersion_);
      }
      if (!getStationVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, stationVersion_);
      }
      if (!getAxialityVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, axialityVersion_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage)) {
        return super.equals(obj);
      }
      com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage other = (com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage) obj;

      boolean result = true;
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && getPlatform()
          .equals(other.getPlatform());
      result = result && getSession()
          .equals(other.getSession());
      result = result && getSectionVersion()
          .equals(other.getSectionVersion());
      result = result && getStationVersion()
          .equals(other.getStationVersion());
      result = result && getAxialityVersion()
          .equals(other.getAxialityVersion());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatform().hashCode();
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
      hash = (37 * hash) + SECTIONVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getSectionVersion().hashCode();
      hash = (37 * hash) + STATIONVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getStationVersion().hashCode();
      hash = (37 * hash) + AXIALITYVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getAxialityVersion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetHighSpeedSectionRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetHighSpeedSectionRequestMessage)
        com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.cqjw.request.GetHighSpeedSectionRequest.internal_static_GetHighSpeedSectionRequestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.cqjw.request.GetHighSpeedSectionRequest.internal_static_GetHighSpeedSectionRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage.class, com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage.Builder.class);
      }

      // Construct using com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = "";

        platform_ = "";

        session_ = "";

        sectionVersion_ = "";

        stationVersion_ = "";

        axialityVersion_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.cqjw.request.GetHighSpeedSectionRequest.internal_static_GetHighSpeedSectionRequestMessage_descriptor;
      }

      public com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage getDefaultInstanceForType() {
        return com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage.getDefaultInstance();
      }

      public com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage build() {
        com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage buildPartial() {
        com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage result = new com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage(this);
        result.version_ = version_;
        result.platform_ = platform_;
        result.session_ = session_;
        result.sectionVersion_ = sectionVersion_;
        result.stationVersion_ = stationVersion_;
        result.axialityVersion_ = axialityVersion_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage) {
          return mergeFrom((com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage other) {
        if (other == com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage.getDefaultInstance()) return this;
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getPlatform().isEmpty()) {
          platform_ = other.platform_;
          onChanged();
        }
        if (!other.getSession().isEmpty()) {
          session_ = other.session_;
          onChanged();
        }
        if (!other.getSectionVersion().isEmpty()) {
          sectionVersion_ = other.sectionVersion_;
          onChanged();
        }
        if (!other.getStationVersion().isEmpty()) {
          stationVersion_ = other.stationVersion_;
          onChanged();
        }
        if (!other.getAxialityVersion().isEmpty()) {
          axialityVersion_ = other.axialityVersion_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>optional string version = 1;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 1;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object platform_ = "";
      /**
       * <pre>
       *平台
       * </pre>
       *
       * <code>optional string platform = 2;</code>
       */
      public java.lang.String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          platform_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *平台
       * </pre>
       *
       * <code>optional string platform = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        java.lang.Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *平台
       * </pre>
       *
       * <code>optional string platform = 2;</code>
       */
      public Builder setPlatform(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *平台
       * </pre>
       *
       * <code>optional string platform = 2;</code>
       */
      public Builder clearPlatform() {
        
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *平台
       * </pre>
       *
       * <code>optional string platform = 2;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        platform_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object session_ = "";
      /**
       * <pre>
       *登錄成功返回的會話
       * </pre>
       *
       * <code>optional string session = 3;</code>
       */
      public java.lang.String getSession() {
        java.lang.Object ref = session_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          session_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *登錄成功返回的會話
       * </pre>
       *
       * <code>optional string session = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionBytes() {
        java.lang.Object ref = session_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          session_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *登錄成功返回的會話
       * </pre>
       *
       * <code>optional string session = 3;</code>
       */
      public Builder setSession(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *登錄成功返回的會話
       * </pre>
       *
       * <code>optional string session = 3;</code>
       */
      public Builder clearSession() {
        
        session_ = getDefaultInstance().getSession();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *登錄成功返回的會話
       * </pre>
       *
       * <code>optional string session = 3;</code>
       */
      public Builder setSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        session_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sectionVersion_ = "";
      /**
       * <pre>
       *当前高速路段配置版本
       * </pre>
       *
       * <code>optional string sectionVersion = 4;</code>
       */
      public java.lang.String getSectionVersion() {
        java.lang.Object ref = sectionVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sectionVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *当前高速路段配置版本
       * </pre>
       *
       * <code>optional string sectionVersion = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSectionVersionBytes() {
        java.lang.Object ref = sectionVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sectionVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *当前高速路段配置版本
       * </pre>
       *
       * <code>optional string sectionVersion = 4;</code>
       */
      public Builder setSectionVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sectionVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前高速路段配置版本
       * </pre>
       *
       * <code>optional string sectionVersion = 4;</code>
       */
      public Builder clearSectionVersion() {
        
        sectionVersion_ = getDefaultInstance().getSectionVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前高速路段配置版本
       * </pre>
       *
       * <code>optional string sectionVersion = 4;</code>
       */
      public Builder setSectionVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sectionVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stationVersion_ = "";
      /**
       * <pre>
       *当前高速路站配置版本
       * </pre>
       *
       * <code>optional string stationVersion = 5;</code>
       */
      public java.lang.String getStationVersion() {
        java.lang.Object ref = stationVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stationVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *当前高速路站配置版本
       * </pre>
       *
       * <code>optional string stationVersion = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStationVersionBytes() {
        java.lang.Object ref = stationVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stationVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *当前高速路站配置版本
       * </pre>
       *
       * <code>optional string stationVersion = 5;</code>
       */
      public Builder setStationVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stationVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前高速路站配置版本
       * </pre>
       *
       * <code>optional string stationVersion = 5;</code>
       */
      public Builder clearStationVersion() {
        
        stationVersion_ = getDefaultInstance().getStationVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前高速路站配置版本
       * </pre>
       *
       * <code>optional string stationVersion = 5;</code>
       */
      public Builder setStationVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stationVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object axialityVersion_ = "";
      /**
       * <pre>
       *当前轴性版本
       * </pre>
       *
       * <code>optional string axialityVersion = 6;</code>
       */
      public java.lang.String getAxialityVersion() {
        java.lang.Object ref = axialityVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          axialityVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *当前轴性版本
       * </pre>
       *
       * <code>optional string axialityVersion = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAxialityVersionBytes() {
        java.lang.Object ref = axialityVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          axialityVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *当前轴性版本
       * </pre>
       *
       * <code>optional string axialityVersion = 6;</code>
       */
      public Builder setAxialityVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        axialityVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前轴性版本
       * </pre>
       *
       * <code>optional string axialityVersion = 6;</code>
       */
      public Builder clearAxialityVersion() {
        
        axialityVersion_ = getDefaultInstance().getAxialityVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前轴性版本
       * </pre>
       *
       * <code>optional string axialityVersion = 6;</code>
       */
      public Builder setAxialityVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        axialityVersion_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:GetHighSpeedSectionRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:GetHighSpeedSectionRequestMessage)
    private static final com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage();
    }

    public static com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetHighSpeedSectionRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetHighSpeedSectionRequestMessage>() {
      public GetHighSpeedSectionRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetHighSpeedSectionRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetHighSpeedSectionRequestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetHighSpeedSectionRequestMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.cqjw.request.GetHighSpeedSectionRequest.GetHighSpeedSectionRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetHighSpeedSectionRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetHighSpeedSectionRequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n GetHighSpeedSectionRequest.proto\"\240\001\n!G" +
      "etHighSpeedSectionRequestMessage\022\017\n\007vers" +
      "ion\030\001 \001(\t\022\020\n\010platform\030\002 \001(\t\022\017\n\007session\030\003" +
      " \001(\t\022\026\n\016sectionVersion\030\004 \001(\t\022\026\n\016stationV" +
      "ersion\030\005 \001(\t\022\027\n\017axialityVersion\030\006 \001(\tB2\n" +
      "\024com.yzh.cqjw.requestB\032GetHighSpeedSecti" +
      "onRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetHighSpeedSectionRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetHighSpeedSectionRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetHighSpeedSectionRequestMessage_descriptor,
        new java.lang.String[] { "Version", "Platform", "Session", "SectionVersion", "StationVersion", "AxialityVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
