// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushRequest.proto

package com.yzh.cqjw.request;

public final class PushRequest {
  private PushRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PushRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PushRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *要推送的用户ID
     * </pre>
     *
     * <code>optional int64 userid = 1;</code>
     */
    long getUserid();

    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>optional string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>optional string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>optional string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>optional string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     **
     * 消息类型：
     *     违章查询  illegalQuery
     *     活动消息  activityMessage
     *     路况消息  conditionMessage
     *     交通路况  trafficCondition
     * </pre>
     *
     * <code>optional string messageType = 4;</code>
     */
    java.lang.String getMessageType();
    /**
     * <pre>
     **
     * 消息类型：
     *     违章查询  illegalQuery
     *     活动消息  activityMessage
     *     路况消息  conditionMessage
     *     交通路况  trafficCondition
     * </pre>
     *
     * <code>optional string messageType = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageTypeBytes();

    /**
     * <pre>
     *主键
     * </pre>
     *
     * <code>optional int64 referenceId = 5;</code>
     */
    long getReferenceId();

    /**
     * <code>optional string channelId = 6;</code>
     */
    java.lang.String getChannelId();
    /**
     * <code>optional string channelId = 6;</code>
     */
    com.google.protobuf.ByteString
        getChannelIdBytes();

    /**
     * <pre>
     *0  全部   1  按tag,   2 按用户
     * </pre>
     *
     * <code>optional int32 type = 7;</code>
     */
    int getType();

    /**
     * <code>optional string tag = 8;</code>
     */
    java.lang.String getTag();
    /**
     * <code>optional string tag = 8;</code>
     */
    com.google.protobuf.ByteString
        getTagBytes();

    /**
     * <pre>
     *操作员
     * </pre>
     *
     * <code>optional int64 operId = 9;</code>
     */
    long getOperId();

    /**
     * <pre>
     *平台  Android/IOS/Android Pad/iPad
     * </pre>
     *
     * <code>optional string platform = 10;</code>
     */
    java.lang.String getPlatform();
    /**
     * <pre>
     *平台  Android/IOS/Android Pad/iPad
     * </pre>
     *
     * <code>optional string platform = 10;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();

    /**
     * <pre>
     *手机
     * </pre>
     *
     * <code>optional string phone = 11;</code>
     */
    java.lang.String getPhone();
    /**
     * <pre>
     *手机
     * </pre>
     *
     * <code>optional string phone = 11;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();
  }
  /**
   * Protobuf type {@code PushRequestMessage}
   */
  public  static final class PushRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PushRequestMessage)
      PushRequestMessageOrBuilder {
    // Use PushRequestMessage.newBuilder() to construct.
    private PushRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushRequestMessage() {
      userid_ = 0L;
      title_ = "";
      description_ = "";
      messageType_ = "";
      referenceId_ = 0L;
      channelId_ = "";
      type_ = 0;
      tag_ = "";
      operId_ = 0L;
      platform_ = "";
      phone_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PushRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userid_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              messageType_ = s;
              break;
            }
            case 40: {

              referenceId_ = input.readInt64();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              channelId_ = s;
              break;
            }
            case 56: {

              type_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              tag_ = s;
              break;
            }
            case 72: {

              operId_ = input.readInt64();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              platform_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yzh.cqjw.request.PushRequest.internal_static_PushRequestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yzh.cqjw.request.PushRequest.internal_static_PushRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yzh.cqjw.request.PushRequest.PushRequestMessage.class, com.yzh.cqjw.request.PushRequest.PushRequestMessage.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userid_;
    /**
     * <pre>
     *要推送的用户ID
     * </pre>
     *
     * <code>optional int64 userid = 1;</code>
     */
    public long getUserid() {
      return userid_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>optional string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>optional string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object messageType_;
    /**
     * <pre>
     **
     * 消息类型：
     *     违章查询  illegalQuery
     *     活动消息  activityMessage
     *     路况消息  conditionMessage
     *     交通路况  trafficCondition
     * </pre>
     *
     * <code>optional string messageType = 4;</code>
     */
    public java.lang.String getMessageType() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 消息类型：
     *     违章查询  illegalQuery
     *     活动消息  activityMessage
     *     路况消息  conditionMessage
     *     交通路况  trafficCondition
     * </pre>
     *
     * <code>optional string messageType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERENCEID_FIELD_NUMBER = 5;
    private long referenceId_;
    /**
     * <pre>
     *主键
     * </pre>
     *
     * <code>optional int64 referenceId = 5;</code>
     */
    public long getReferenceId() {
      return referenceId_;
    }

    public static final int CHANNELID_FIELD_NUMBER = 6;
    private volatile java.lang.Object channelId_;
    /**
     * <code>optional string channelId = 6;</code>
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string channelId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 7;
    private int type_;
    /**
     * <pre>
     *0  全部   1  按tag,   2 按用户
     * </pre>
     *
     * <code>optional int32 type = 7;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int TAG_FIELD_NUMBER = 8;
    private volatile java.lang.Object tag_;
    /**
     * <code>optional string tag = 8;</code>
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      }
    }
    /**
     * <code>optional string tag = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERID_FIELD_NUMBER = 9;
    private long operId_;
    /**
     * <pre>
     *操作员
     * </pre>
     *
     * <code>optional int64 operId = 9;</code>
     */
    public long getOperId() {
      return operId_;
    }

    public static final int PLATFORM_FIELD_NUMBER = 10;
    private volatile java.lang.Object platform_;
    /**
     * <pre>
     *平台  Android/IOS/Android Pad/iPad
     * </pre>
     *
     * <code>optional string platform = 10;</code>
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *平台  Android/IOS/Android Pad/iPad
     * </pre>
     *
     * <code>optional string platform = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 11;
    private volatile java.lang.Object phone_;
    /**
     * <pre>
     *手机
     * </pre>
     *
     * <code>optional string phone = 11;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *手机
     * </pre>
     *
     * <code>optional string phone = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userid_ != 0L) {
        output.writeInt64(1, userid_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      if (!getMessageTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, messageType_);
      }
      if (referenceId_ != 0L) {
        output.writeInt64(5, referenceId_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, channelId_);
      }
      if (type_ != 0) {
        output.writeInt32(7, type_);
      }
      if (!getTagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tag_);
      }
      if (operId_ != 0L) {
        output.writeInt64(9, operId_);
      }
      if (!getPlatformBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, platform_);
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, phone_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userid_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      if (!getMessageTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, messageType_);
      }
      if (referenceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, referenceId_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, channelId_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, type_);
      }
      if (!getTagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tag_);
      }
      if (operId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, operId_);
      }
      if (!getPlatformBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, platform_);
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, phone_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yzh.cqjw.request.PushRequest.PushRequestMessage)) {
        return super.equals(obj);
      }
      com.yzh.cqjw.request.PushRequest.PushRequestMessage other = (com.yzh.cqjw.request.PushRequest.PushRequestMessage) obj;

      boolean result = true;
      result = result && (getUserid()
          == other.getUserid());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && getMessageType()
          .equals(other.getMessageType());
      result = result && (getReferenceId()
          == other.getReferenceId());
      result = result && getChannelId()
          .equals(other.getChannelId());
      result = result && (getType()
          == other.getType());
      result = result && getTag()
          .equals(other.getTag());
      result = result && (getOperId()
          == other.getOperId());
      result = result && getPlatform()
          .equals(other.getPlatform());
      result = result && getPhone()
          .equals(other.getPhone());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserid());
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType().hashCode();
      hash = (37 * hash) + REFERENCEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReferenceId());
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTag().hashCode();
      hash = (37 * hash) + OPERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOperId());
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatform().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yzh.cqjw.request.PushRequest.PushRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PushRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PushRequestMessage)
        com.yzh.cqjw.request.PushRequest.PushRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yzh.cqjw.request.PushRequest.internal_static_PushRequestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yzh.cqjw.request.PushRequest.internal_static_PushRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yzh.cqjw.request.PushRequest.PushRequestMessage.class, com.yzh.cqjw.request.PushRequest.PushRequestMessage.Builder.class);
      }

      // Construct using com.yzh.cqjw.request.PushRequest.PushRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userid_ = 0L;

        title_ = "";

        description_ = "";

        messageType_ = "";

        referenceId_ = 0L;

        channelId_ = "";

        type_ = 0;

        tag_ = "";

        operId_ = 0L;

        platform_ = "";

        phone_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yzh.cqjw.request.PushRequest.internal_static_PushRequestMessage_descriptor;
      }

      public com.yzh.cqjw.request.PushRequest.PushRequestMessage getDefaultInstanceForType() {
        return com.yzh.cqjw.request.PushRequest.PushRequestMessage.getDefaultInstance();
      }

      public com.yzh.cqjw.request.PushRequest.PushRequestMessage build() {
        com.yzh.cqjw.request.PushRequest.PushRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yzh.cqjw.request.PushRequest.PushRequestMessage buildPartial() {
        com.yzh.cqjw.request.PushRequest.PushRequestMessage result = new com.yzh.cqjw.request.PushRequest.PushRequestMessage(this);
        result.userid_ = userid_;
        result.title_ = title_;
        result.description_ = description_;
        result.messageType_ = messageType_;
        result.referenceId_ = referenceId_;
        result.channelId_ = channelId_;
        result.type_ = type_;
        result.tag_ = tag_;
        result.operId_ = operId_;
        result.platform_ = platform_;
        result.phone_ = phone_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yzh.cqjw.request.PushRequest.PushRequestMessage) {
          return mergeFrom((com.yzh.cqjw.request.PushRequest.PushRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yzh.cqjw.request.PushRequest.PushRequestMessage other) {
        if (other == com.yzh.cqjw.request.PushRequest.PushRequestMessage.getDefaultInstance()) return this;
        if (other.getUserid() != 0L) {
          setUserid(other.getUserid());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getMessageType().isEmpty()) {
          messageType_ = other.messageType_;
          onChanged();
        }
        if (other.getReferenceId() != 0L) {
          setReferenceId(other.getReferenceId());
        }
        if (!other.getChannelId().isEmpty()) {
          channelId_ = other.channelId_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getTag().isEmpty()) {
          tag_ = other.tag_;
          onChanged();
        }
        if (other.getOperId() != 0L) {
          setOperId(other.getOperId());
        }
        if (!other.getPlatform().isEmpty()) {
          platform_ = other.platform_;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yzh.cqjw.request.PushRequest.PushRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yzh.cqjw.request.PushRequest.PushRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userid_ ;
      /**
       * <pre>
       *要推送的用户ID
       * </pre>
       *
       * <code>optional int64 userid = 1;</code>
       */
      public long getUserid() {
        return userid_;
      }
      /**
       * <pre>
       *要推送的用户ID
       * </pre>
       *
       * <code>optional int64 userid = 1;</code>
       */
      public Builder setUserid(long value) {
        
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *要推送的用户ID
       * </pre>
       *
       * <code>optional int64 userid = 1;</code>
       */
      public Builder clearUserid() {
        
        userid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>optional string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>optional string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>optional string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>optional string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>optional string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>optional string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>optional string description = 3;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>optional string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageType_ = "";
      /**
       * <pre>
       **
       * 消息类型：
       *     违章查询  illegalQuery
       *     活动消息  activityMessage
       *     路况消息  conditionMessage
       *     交通路况  trafficCondition
       * </pre>
       *
       * <code>optional string messageType = 4;</code>
       */
      public java.lang.String getMessageType() {
        java.lang.Object ref = messageType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 消息类型：
       *     违章查询  illegalQuery
       *     活动消息  activityMessage
       *     路况消息  conditionMessage
       *     交通路况  trafficCondition
       * </pre>
       *
       * <code>optional string messageType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageTypeBytes() {
        java.lang.Object ref = messageType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 消息类型：
       *     违章查询  illegalQuery
       *     活动消息  activityMessage
       *     路况消息  conditionMessage
       *     交通路况  trafficCondition
       * </pre>
       *
       * <code>optional string messageType = 4;</code>
       */
      public Builder setMessageType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 消息类型：
       *     违章查询  illegalQuery
       *     活动消息  activityMessage
       *     路况消息  conditionMessage
       *     交通路况  trafficCondition
       * </pre>
       *
       * <code>optional string messageType = 4;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = getDefaultInstance().getMessageType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 消息类型：
       *     违章查询  illegalQuery
       *     活动消息  activityMessage
       *     路况消息  conditionMessage
       *     交通路况  trafficCondition
       * </pre>
       *
       * <code>optional string messageType = 4;</code>
       */
      public Builder setMessageTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageType_ = value;
        onChanged();
        return this;
      }

      private long referenceId_ ;
      /**
       * <pre>
       *主键
       * </pre>
       *
       * <code>optional int64 referenceId = 5;</code>
       */
      public long getReferenceId() {
        return referenceId_;
      }
      /**
       * <pre>
       *主键
       * </pre>
       *
       * <code>optional int64 referenceId = 5;</code>
       */
      public Builder setReferenceId(long value) {
        
        referenceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主键
       * </pre>
       *
       * <code>optional int64 referenceId = 5;</code>
       */
      public Builder clearReferenceId() {
        
        referenceId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object channelId_ = "";
      /**
       * <code>optional string channelId = 6;</code>
       */
      public java.lang.String getChannelId() {
        java.lang.Object ref = channelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string channelId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getChannelIdBytes() {
        java.lang.Object ref = channelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string channelId = 6;</code>
       */
      public Builder setChannelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string channelId = 6;</code>
       */
      public Builder clearChannelId() {
        
        channelId_ = getDefaultInstance().getChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string channelId = 6;</code>
       */
      public Builder setChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channelId_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       *0  全部   1  按tag,   2 按用户
       * </pre>
       *
       * <code>optional int32 type = 7;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *0  全部   1  按tag,   2 按用户
       * </pre>
       *
       * <code>optional int32 type = 7;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0  全部   1  按tag,   2 按用户
       * </pre>
       *
       * <code>optional int32 type = 7;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object tag_ = "";
      /**
       * <code>optional string tag = 8;</code>
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tag = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tag = 8;</code>
       */
      public Builder setTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tag = 8;</code>
       */
      public Builder clearTag() {
        
        tag_ = getDefaultInstance().getTag();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tag = 8;</code>
       */
      public Builder setTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tag_ = value;
        onChanged();
        return this;
      }

      private long operId_ ;
      /**
       * <pre>
       *操作员
       * </pre>
       *
       * <code>optional int64 operId = 9;</code>
       */
      public long getOperId() {
        return operId_;
      }
      /**
       * <pre>
       *操作员
       * </pre>
       *
       * <code>optional int64 operId = 9;</code>
       */
      public Builder setOperId(long value) {
        
        operId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *操作员
       * </pre>
       *
       * <code>optional int64 operId = 9;</code>
       */
      public Builder clearOperId() {
        
        operId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object platform_ = "";
      /**
       * <pre>
       *平台  Android/IOS/Android Pad/iPad
       * </pre>
       *
       * <code>optional string platform = 10;</code>
       */
      public java.lang.String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          platform_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *平台  Android/IOS/Android Pad/iPad
       * </pre>
       *
       * <code>optional string platform = 10;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        java.lang.Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *平台  Android/IOS/Android Pad/iPad
       * </pre>
       *
       * <code>optional string platform = 10;</code>
       */
      public Builder setPlatform(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *平台  Android/IOS/Android Pad/iPad
       * </pre>
       *
       * <code>optional string platform = 10;</code>
       */
      public Builder clearPlatform() {
        
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *平台  Android/IOS/Android Pad/iPad
       * </pre>
       *
       * <code>optional string platform = 10;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        platform_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <pre>
       *手机
       * </pre>
       *
       * <code>optional string phone = 11;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *手机
       * </pre>
       *
       * <code>optional string phone = 11;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *手机
       * </pre>
       *
       * <code>optional string phone = 11;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机
       * </pre>
       *
       * <code>optional string phone = 11;</code>
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机
       * </pre>
       *
       * <code>optional string phone = 11;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PushRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:PushRequestMessage)
    private static final com.yzh.cqjw.request.PushRequest.PushRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yzh.cqjw.request.PushRequest.PushRequestMessage();
    }

    public static com.yzh.cqjw.request.PushRequest.PushRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<PushRequestMessage>() {
      public PushRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PushRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PushRequestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PushRequestMessage> getParserForType() {
      return PARSER;
    }

    public com.yzh.cqjw.request.PushRequest.PushRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushRequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PushRequest.proto\"\321\001\n\022PushRequestMessa" +
      "ge\022\016\n\006userid\030\001 \001(\003\022\r\n\005title\030\002 \001(\t\022\023\n\013des" +
      "cription\030\003 \001(\t\022\023\n\013messageType\030\004 \001(\t\022\023\n\013r" +
      "eferenceId\030\005 \001(\003\022\021\n\tchannelId\030\006 \001(\t\022\014\n\004t" +
      "ype\030\007 \001(\005\022\013\n\003tag\030\010 \001(\t\022\016\n\006operId\030\t \001(\003\022\020" +
      "\n\010platform\030\n \001(\t\022\r\n\005phone\030\013 \001(\tB#\n\024com.y" +
      "zh.cqjw.requestB\013PushRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PushRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PushRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushRequestMessage_descriptor,
        new java.lang.String[] { "Userid", "Title", "Description", "MessageType", "ReferenceId", "ChannelId", "Type", "Tag", "OperId", "Platform", "Phone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
